[project]
name = "discord-vault"
version = "0.1.0"
description = "Discord個人データ保存Bot - 個人用データを安全に保存・管理"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.1.0",
]
